# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-03 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=32, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=32, null=True)),
                ('requested_at', models.DateTimeField()),
                ('beneficiary', models.CharField(blank=True, max_length=32, null=True)),
                ('sender_partner_id', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='PHP', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('FT', 'Fund Transfer'), ('INSTA', 'Instapay Fund Transfer')], max_length=8)),
                ('sender_data', models.TextField(blank=True, null=True)),
                ('beneficiary_data', models.TextField(blank=True, null=True)),
                ('remittance_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
