# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-04 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_unionbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransfer',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
