# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_unionbank', '0002_fundtransfer_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstapayBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('brstn', models.CharField(blank=True, max_length=128, null=True)),
                ('remarks', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Failed'), ('P', 'Pending')], default='P', max_length=8),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundtransfer',
            name='channel',
            field=models.CharField(choices=[('UBP', 'Fund Transfer'), ('IPY', 'Instapay Fund Transfer'), ('PSO', 'PESONet Fund Transfer')], max_length=8),
        ),
    ]
