# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_unionbank', '0003_auto_20200111_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PESONetBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=128)),
                ('brstn', models.CharField(blank=True, max_length=128, null=True)),
                ('remarks', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
